### PR TITLE
Created a Norwegian translation

### PR DESCRIPTION
**Pull request by DandelionSprout**
I just as well just created a Norwegian translation of strings.xml, in the hopes that this project accepts translations.

### CODE REVIEW

**Comment by martinmarinov** [comment]
Thanks!

**Comment by martinmarinov** [comment]
By the way @DandelionSprout you can translate the main Aerial TV app here https://ackuna.com/translate-/aerialtv/at-a-glance/norwegian in case you are interested :)

**Comment by DandelionSprout** [comment]
Ah, thanks for the headsup. I'll get around to translating that app too.

**Comment by DandelionSprout** [comment]
I believe that the translation of Aerial TV should now be completed over on Ackuna as well.

**Pull request merged**
